language: java
sudo: required
script: mvn clean verify

jdk:
  - openjdk11

before_install:
  - chmod +x mvnw
  
jobs:
  include:
    - stage: Master-Push
      if: branch = master AND type = push
      script:
        - pyenv global 3.7.1
        - pip install -U pip
        - pip install awscli
        - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
        - echo "CI/CD Starting for $BRANCH"
        - python env_injection.py
        - mvn clean package spring-boot:repackage
        - eb deploy
      after_success:
        - echo "Deployed Successfully"

    - stage: Master-PR
      if: branch = master AND type = pull_request
      script:
        - echo "CI/CD Starting for $BRANCH"
        - python env_injection.py
        - mvn clean package spring-boot:repackage
      after_success:
        - echo "CI Successfully"

    - stage: Dev-Push
      if: branch = dev AND type = push
      script:
        - echo "CI/CD Starting for $BRANCH"
        - python env_injection.py
        - mvn clean package spring-boot:repackage
      after_success:
        - echo "CI Successfully"