branch-defaults:
  master:
    environment: WileyTestBackend-env
environment-defaults:
  WileyTestBackend-env:
    branch: null
    repository: null
global:
  application_name: wiley-test-backend
  default_ec2_keyname: null
  default_platform: Corretto 11 running on 64bit Amazon Linux 2
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
deploy:
  artifact: target/wileytest-0.0.1-SNAPSHOT.jar