spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/wiley?useSSL=false'
    username: root
    password: ''

  jpa:
      show-sql: true
      hibernate:
          ddl-auto: update
          naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
          hibernate:
              dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: xxxxx
            clientSecret: xxxx
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

  mail:
    host: smtp.sendgrid.net
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    username: username
    password: password

server:
  port: 5000
  error: 
    include-message: always

app:
  auth:
    tokenSecret: INgkFkn6DNv5bvHBOOdWom0S4nYt
    tokenExpirationMsec: 2592000000
      